
#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define	BUFF_SIZE_LONG	100000
#define	BUFF_SIZE_SHORT	512

#define	MODEL_STATUS_UNKNOWN	0
#define	MODEL_STATUS_EST	1
#define	MODEL_STATUS_ESTC	2
#define	MODEL_STATUS_INF	3

#endif

